name: Data Pipeline

on:
  push:
    paths:
      - 'data/**'
      - 'src/data_processing/**'
  workflow_dispatch:

jobs:
  data-processing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data preparation
      run: python main.py --prepare
      
    - name: Run data tests
      run: |
        python -m pytest tests/test_data.py
        
    - name: Upload processed data
      uses: actions/upload-artifact@v2
      with:
        name: prepared-data
        path: prepared_data.joblib
        
    - name: Notify on completion
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const { status } = process.env;
          const message = `Data pipeline completed with status: ${status}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });