name: Model Training

on:
  workflow_run:
    workflows: ["Data Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  train-and-evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download processed data
      uses: actions/download-artifact@v2
      with:
        name: prepared-data
        
    - name: Train model
      run: python main.py --train
      
    - name: Evaluate model
      run: python main.py --evaluate
      
    - name: Run model tests
      run: |
        python -m pytest tests/test_model.py
        
    - name: Upload model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: model-artifacts
        path: |
          model.joblib
          confusion_matrix.png
          classification_report.txt
          
    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{secrets.MAIL_SERVER}}
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Model Training Pipeline Status
        body: Model training completed. Check results in GitHub Actions.
        to: ${{secrets.NOTIFICATION_EMAIL}}
        from: GitHub Actions